name: "terraform-test"    # Workflow Name
on: workflow_dispatch     #   Trigger None
permissions:
  contents: read
  id-token: write
jobs:
  init-plan:
    name: init-plan
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v6..1
    - name: Azure Login               # Service-Connection
      uses: Azure/login@v2.3.0
      with:
        client-id: "ec318753-8441-4718-8d01-3a7c4aeef626"
        tenant-id: "0c30cc1a-956a-4c45-9571-96bfaa75a9af"
        subscription-id: "de1c1815-4f90-412b-9551-d55f0de9407d"
        
       
          
